name: Setup repository
on: workflow_dispatch

permissions:
  pages: read
  contents: write
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: "npm"
    - name: Setup Pages
      id: configure-pages
      uses: actions/configure-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        npm ci
        npm run setup-repository --repository=${{ github.repository }} --pages_basepath=${{ steps.configure-pages.outputs.base_path }} --pages_baseurl=${{ steps.configure-pages.outputs.base_url }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: setup repository'
        title: 'chore: setup repository'
        body: |
          This is an automated pull request to setup the repository.
          It will be automatically closed if no commits are made to this branch within 30 days.
        branch: setup-repository
        branch-suffix: timestamp
        delete-branch: true
